import { ThemeProvider } from "@/app/providers/theme-provider";
import { cn } from "@repo/ui";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const macan = localFont({
  src: [
    {
      path: "../../public/fonts/MacanBook.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/MacanBookItalic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../../public/fonts/MacanMedium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/MacanMediumItalic.woff2",
      weight: "500",
      style: "italic",
    },
    {
      path: "../../public/fonts/MacanSemibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/MacanSemiboldItalic.woff2",
      weight: "600",
      style: "italic",
    },
    {
      path: "../../public/fonts/MacanBold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/MacanBoldItalic.woff2",
      weight: "700",
      style: "italic",
    },
  ],
});

export const metadata: Metadata = {
  title: "Warp Calendar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(macan.className, "antialiased")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
