import { CalendarEvent, Person } from "@repo/types";

const people: Record<string, Person> = {
  adam: {
    id: "p1",
    firstName: "Adam",
    lastName: "Rankin",
    avatar: "/people/adam-rankin.jpeg",
  },
  aj: {
    id: "p2",
    firstName: "AJ",
    lastName: "Naqib",
    avatar: "/people/aj-naqib.png",
  },
  alexis: {
    id: "p3",
    firstName: "Alexis",
    lastName: "Stovall",
    avatar: "/people/alexis-stovall.jpeg",
  },
  allan: {
    id: "p4",
    firstName: "Allan",
    lastName: "Lvov",
    avatar: "/people/allan-lvov.jpeg",
  },
  aneesh: {
    id: "p5",
    firstName: "Aneesh",
    lastName: "Boreda",
    avatar: "/people/aneesh-boreda.jpeg",
  },
  ash: {
    id: "p6",
    firstName: "Ash",
    lastName: "S",
    avatar: "/people/ash-s.jpeg",
  },
  asongna: {
    id: "p7",
    firstName: "Asongna",
    lastName: "Tajong",
    avatar: "/people/asongna-tajong.jpeg",
  },
  ayush: {
    id: "p8",
    firstName: "Ayush",
    lastName: "Sharma",
    avatar: "/people/ayush-sharma.jpeg",
  },
  benjamin: {
    id: "p9",
    firstName: "Benjamin",
    lastName: "Shein",
    avatar: "/people/benjamin-shein.jpeg",
  },
  brandon: {
    id: "p10",
    firstName: "Brandon",
    lastName: "Novarro",
    avatar: "/people/brandon-novarro.jpeg",
  },
  eliza: {
    id: "p11",
    firstName: "Eliza",
    lastName: "Cain",
    avatar: "/people/eliza-cain.jpeg",
  },
  gaby: {
    id: "p12",
    firstName: "Gaby",
    lastName: "Garcia",
    avatar: "/people/gaby-garcia.jpeg",
  },
  grayson: {
    id: "p13",
    firstName: "Grayson",
    lastName: "Stiles",
    avatar: "/people/grayson-stiles.jpeg",
  },
  hayk: {
    id: "p14",
    firstName: "Hayk",
    lastName: "Ghon",
    avatar: "/people/hayk-ghon.jpeg",
  },
  juliette: {
    id: "p15",
    firstName: "Juliette",
    lastName: "Bolea",
    avatar: "/people/juliette-bolea.jpeg",
  },
  lara: {
    id: "p16",
    firstName: "Lara",
    lastName: "Páircéir",
    avatar: "/people/lara-páircéir.jpeg",
  },
  nicoleChinuntdet: {
    id: "p17",
    firstName: "Nicole",
    lastName: "Chinuntdet",
    avatar: "/people/nicole-chinuntdet.jpeg",
  },
  nicoleSievers: {
    id: "p18",
    firstName: "Nicole",
    lastName: "Sievers",
    avatar: "/people/nicole-sievers.jpeg",
  },
  sara: {
    id: "p19",
    firstName: "Sara",
    lastName: "B",
    avatar: "/people/sara-b.jpeg",
  },
  sarah: {
    id: "p20",
    firstName: "Sarah",
    lastName: "Hunter",
    avatar: "/people/sarah-hunter.jpeg",
  },
  sasha: {
    id: "p21",
    firstName: "Sasha",
    lastName: "A",
    avatar: "/people/sasha-a.jpeg",
  },
  sidra: {
    id: "p22",
    firstName: "Sidra",
    lastName: "Saleem",
    avatar: "/people/sidra-saleem.png",
  },
  thiago: {
    id: "p23",
    firstName: "Thiago",
    lastName: "Bocayuva",
    avatar: "/people/thiago-bocayuva.png",
  },
  will: {
    id: "p24",
    firstName: "Will",
    lastName: "Kostrzewsky",
    avatar: "/people/will-kostrzewsky.jpeg",
  },
  wyatt: {
    id: "p25",
    firstName: "Wyatt",
    lastName: "Shulte",
    avatar: "/people/wyatt-shulte.jpeg",
  },
  yuang: {
    id: "p26",
    firstName: "Yuang Patric",
    lastName: "S",
    avatar: "/people/yuang-patric-s.jpeg",
  },
  arnie: {
    id: "p27",
    firstName: "Arnie",
    lastName: "Sandoval",
    avatar: "/people/arnie-sandoval.jpg",
  },
};

export const sampleEvents: CalendarEvent[] = [
  // Early November events
  {
    id: "34",
    title: "Birthday",
    type: "birthday",
    startDate: "2025-11-03",
    allDay: true,
    person: people.hayk,
  },
  {
    id: "35",
    title: "2 Years at Warp",
    type: "anniversary",
    startDate: "2025-11-05",
    allDay: true,
    person: people.sasha,
    metadata: { yearsOfService: 2 },
  },
  {
    id: "36",
    title: "PTO",
    type: "time-off",
    startDate: "2025-11-04",
    endDate: "2025-11-06",
    allDay: true,
    person: people.gaby,
    description: "Family visit",
  },
  {
    id: "37",
    title: "Product Launch",
    type: "deadline",
    startDate: "2025-11-07T10:00:00-08:00",
    description: "V2.0 release",
  },
  {
    id: "38",
    title: "Birthday",
    type: "birthday",
    startDate: "2025-11-10",
    allDay: true,
    person: people.wyatt,
  },
  {
    id: "39",
    title: "Veterans Day",
    type: "company-event",
    startDate: "2025-11-11",
    allDay: true,
    description: "Company Holiday",
  },
  {
    id: "40",
    title: "PTO",
    type: "time-off",
    startDate: "2025-11-12",
    endDate: "2025-11-14",
    allDay: true,
    person: people.brandon,
  },
  {
    id: "41",
    title: "4 Years at Warp",
    type: "anniversary",
    startDate: "2025-11-13",
    allDay: true,
    person: people.juliette,
    metadata: { yearsOfService: 4 },
  },
  {
    id: "42",
    title: "Design Sprint",
    type: "company-event",
    startDate: "2025-11-17T09:00:00-08:00",
    endDate: "2025-11-17T17:00:00-08:00",
    description: "Q1 planning",
  },
  {
    id: "43",
    title: "Birthday",
    type: "birthday",
    startDate: "2025-11-18",
    allDay: true,
    person: people.aneesh,
  },
  {
    id: "44",
    title: "PTO",
    type: "time-off",
    startDate: "2025-11-19",
    allDay: true,
    person: people.sidra,
  },
  {
    id: "45",
    title: "1 Year at Warp",
    type: "anniversary",
    startDate: "2025-11-20",
    allDay: true,
    person: people.yuang,
    metadata: { yearsOfService: 1 },
  },
  {
    id: "46",
    title: "Team Offsite",
    type: "company-event",
    startDate: "2025-11-21",
    endDate: "2025-11-22",
    allDay: true,
    description: "Annual team building",
  },

  // Multi-day PTO (Thursday to Tuesday)
  {
    id: "1",
    title: "PTO",
    type: "time-off",
    startDate: "2025-11-27",
    endDate: "2025-12-02",
    allDay: true,
    person: people.adam,
    description: "Family vacation",
  },

  // Overlapping PTO
  {
    id: "2",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-01",
    endDate: "2025-12-03",
    allDay: true,
    person: people.alexis,
  },

  // Birthday during vacation (overlapping event types)
  {
    id: "3",
    title: "Birthday",
    type: "birthday",
    startDate: "2025-11-29",
    allDay: true,
    person: people.sarah,
  },

  // Additional December 1st events for testing
  {
    id: "32",
    title: "Team Standup",
    type: "company-event",
    startDate: "2025-11-29T09:00:00-08:00",
    endDate: "2025-11-29T09:30:00-08:00",
    description: "Daily standup",
  },
  {
    id: "33",
    title: "1:1 with Manager",
    type: "company-event",
    startDate: "2025-11-29T14:00:00-08:00",
    endDate: "2025-11-29T14:30:00-08:00",
    description: "Weekly sync",
  },
  {
    id: "47",
    title: "Birthday",
    type: "birthday",
    startDate: "2025-11-29",
    allDay: true,
    person: people.eliza,
  },
  {
    id: "48",
    title: "Code Review",
    type: "deadline",
    startDate: "2025-11-29T16:00:00-08:00",
    description: "PR review deadline",
  },

  // Work anniversary
  {
    id: "4",
    title: "3 Years at Warp",
    type: "anniversary",
    startDate: "2025-11-25",
    allDay: true,
    person: people.thiago,
    metadata: { yearsOfService: 3 },
  },

  // Multiple meetings at same time (10am overlap) - PST timezone
  {
    id: "5",
    title: "All Hands Meeting",
    type: "company-event",
    startDate: "2025-11-26T10:00:00-08:00",
    endDate: "2025-11-26T11:00:00-08:00",
    description: "Q4 wrap-up",
  },
  {
    id: "6",
    title: "Design Review",
    type: "company-event",
    startDate: "2025-11-26T10:00:00-08:00",
    endDate: "2025-11-26T10:30:00-08:00",
    description: "Weekly design sync",
  },

  // Deadline - EST timezone (different from others)
  {
    id: "7",
    title: "Q4 Reports Due",
    type: "deadline",
    startDate: "2025-12-05T17:00:00-05:00",
    description: "Final submission to finance",
  },

  // Company event - Thanksgiving
  {
    id: "8",
    title: "Thanksgiving",
    type: "company-event",
    startDate: "2025-11-27",
    allDay: true,
    description: "Company Holiday",
  },

  // Company event - Office Holiday Shutdown
  {
    id: "9",
    title: "Office Closed for Holidays",
    type: "company-event",
    startDate: "2025-12-25",
    endDate: "2026-01-02",
    allDay: true,
    description: "Company Holiday",
  },

  // Additional birthday
  {
    id: "10",
    title: "Birthday",
    type: "birthday",
    startDate: "2025-12-10",
    allDay: true,
    person: people.gaby,
  },

  // Another anniversary
  {
    id: "11",
    title: "5 Years at Warp",
    type: "anniversary",
    startDate: "2025-12-15",
    allDay: true,
    person: people.eliza,
    metadata: { yearsOfService: 5 },
  },

  // More PTO
  {
    id: "12",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-22",
    endDate: "2025-12-26",
    allDay: true,
    person: people.benjamin,
    description: "Holiday break",
  },

  // AJ - Birthday
  {
    id: "13",
    title: "Birthday",
    type: "birthday",
    startDate: "2025-11-28",
    allDay: true,
    person: people.aj,
  },

  // Allan - Anniversary
  {
    id: "14",
    title: "2 Years at Warp",
    type: "anniversary",
    startDate: "2025-12-03",
    allDay: true,
    person: people.allan,
    metadata: { yearsOfService: 2 },
  },

  // Aneesh - PTO
  {
    id: "15",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-08",
    endDate: "2025-12-09",
    allDay: true,
    person: people.aneesh,
    description: "Personal days",
  },

  // Ash - Birthday
  {
    id: "16",
    title: "Birthday",
    type: "birthday",
    startDate: "2025-12-12",
    allDay: true,
    person: people.ash,
  },

  // Asongna - Anniversary
  {
    id: "17",
    title: "1 Year at Warp",
    type: "anniversary",
    startDate: "2025-11-29",
    allDay: true,
    person: people.asongna,
    metadata: { yearsOfService: 1 },
  },

  // Ayush - PTO
  {
    id: "18",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-16",
    endDate: "2025-12-17",
    allDay: true,
    person: people.ayush,
  },

  // Brandon - Birthday
  {
    id: "19",
    title: "Birthday",
    type: "birthday",
    startDate: "2025-12-18",
    allDay: true,
    person: people.brandon,
  },

  // Grayson - Anniversary
  {
    id: "20",
    title: "4 Years at Warp",
    type: "anniversary",
    startDate: "2025-12-04",
    allDay: true,
    person: people.grayson,
    metadata: { yearsOfService: 4 },
  },

  // Hayk - PTO
  {
    id: "21",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-11",
    allDay: true,
    person: people.hayk,
    description: "Doctor appointment",
  },

  // Juliette - Birthday
  {
    id: "22",
    title: "Birthday",
    type: "birthday",
    startDate: "2025-12-20",
    allDay: true,
    person: people.juliette,
  },

  // Lara - Anniversary
  {
    id: "23",
    title: "2 Years at Warp",
    type: "anniversary",
    startDate: "2025-12-06",
    allDay: true,
    person: people.lara,
    metadata: { yearsOfService: 2 },
  },

  // Nicole Chinuntdet - PTO
  {
    id: "24",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-13",
    endDate: "2025-12-14",
    allDay: true,
    person: people.nicoleChinuntdet,
  },

  // Nicole Sievers - Birthday
  {
    id: "25",
    title: "Birthday",
    type: "birthday",
    startDate: "2025-11-30",
    allDay: true,
    person: people.nicoleSievers,
  },

  // Sara - Anniversary
  {
    id: "26",
    title: "3 Years at Warp",
    type: "anniversary",
    startDate: "2025-12-07",
    allDay: true,
    person: people.sara,
    metadata: { yearsOfService: 3 },
  },

  // Sasha - PTO
  {
    id: "27",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-19",
    allDay: true,
    person: people.sasha,
    description: "Moving day",
  },

  // Sidra - Birthday
  {
    id: "28",
    title: "Birthday",
    type: "birthday",
    startDate: "2025-12-21",
    allDay: true,
    person: people.sidra,
  },

  // Will - Anniversary
  {
    id: "29",
    title: "6 Years at Warp",
    type: "anniversary",
    startDate: "2025-12-02",
    allDay: true,
    person: people.will,
    metadata: { yearsOfService: 6 },
  },

  // Wyatt - PTO
  {
    id: "30",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-23",
    endDate: "2025-12-24",
    allDay: true,
    person: people.wyatt,
    description: "Holiday travel",
  },

  // Yuang - Birthday
  {
    id: "31",
    title: "Birthday",
    type: "birthday",
    startDate: "2025-12-09",
    allDay: true,
    person: people.yuang,
  },

  // Thanksgiving PTO - Nov 27-28
  {
    id: "49",
    title: "PTO",
    type: "time-off",
    startDate: "2025-11-27",
    endDate: "2025-11-28",
    allDay: true,
    person: people.aj,
  },
  {
    id: "50",
    title: "PTO",
    type: "time-off",
    startDate: "2025-11-27",
    endDate: "2025-11-28",
    allDay: true,
    person: people.alexis,
  },
  {
    id: "51",
    title: "PTO",
    type: "time-off",
    startDate: "2025-11-27",
    endDate: "2025-11-28",
    allDay: true,
    person: people.allan,
  },
  {
    id: "52",
    title: "PTO",
    type: "time-off",
    startDate: "2025-11-27",
    endDate: "2025-11-28",
    allDay: true,
    person: people.aneesh,
  },
  {
    id: "53",
    title: "PTO",
    type: "time-off",
    startDate: "2025-11-27",
    endDate: "2025-11-28",
    allDay: true,
    person: people.ash,
  },
  {
    id: "54",
    title: "PTO",
    type: "time-off",
    startDate: "2025-11-27",
    endDate: "2025-11-28",
    allDay: true,
    person: people.asongna,
  },
  {
    id: "55",
    title: "PTO",
    type: "time-off",
    startDate: "2025-11-27",
    endDate: "2025-11-28",
    allDay: true,
    person: people.ayush,
  },
  {
    id: "56",
    title: "PTO",
    type: "time-off",
    startDate: "2025-11-27",
    endDate: "2025-11-28",
    allDay: true,
    person: people.benjamin,
  },
  {
    id: "57",
    title: "PTO",
    type: "time-off",
    startDate: "2025-11-27",
    endDate: "2025-11-28",
    allDay: true,
    person: people.brandon,
  },
  {
    id: "58",
    title: "PTO",
    type: "time-off",
    startDate: "2025-11-27",
    endDate: "2025-11-28",
    allDay: true,
    person: people.eliza,
  },
  {
    id: "59",
    title: "PTO",
    type: "time-off",
    startDate: "2025-11-27",
    endDate: "2025-11-28",
    allDay: true,
    person: people.gaby,
  },
  {
    id: "60",
    title: "PTO",
    type: "time-off",
    startDate: "2025-11-27",
    endDate: "2025-11-28",
    allDay: true,
    person: people.grayson,
  },
  {
    id: "61",
    title: "PTO",
    type: "time-off",
    startDate: "2025-11-27",
    endDate: "2025-11-28",
    allDay: true,
    person: people.hayk,
  },
  {
    id: "62",
    title: "PTO",
    type: "time-off",
    startDate: "2025-11-27",
    endDate: "2025-11-28",
    allDay: true,
    person: people.juliette,
  },
  {
    id: "63",
    title: "PTO",
    type: "time-off",
    startDate: "2025-11-27",
    endDate: "2025-11-28",
    allDay: true,
    person: people.lara,
  },

  // Holiday Shutdown PTO - Dec 24 to Jan 2 (everyone)
  {
    id: "64",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.adam,
  },
  {
    id: "65",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.aj,
  },
  {
    id: "66",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.alexis,
  },
  {
    id: "67",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.allan,
  },
  {
    id: "68",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.aneesh,
  },
  {
    id: "69",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.ash,
  },
  {
    id: "70",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.asongna,
  },
  {
    id: "71",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.ayush,
  },
  {
    id: "72",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.benjamin,
  },
  {
    id: "73",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.brandon,
  },
  {
    id: "74",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.eliza,
  },
  {
    id: "75",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.gaby,
  },
  {
    id: "76",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.grayson,
  },
  {
    id: "77",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.hayk,
  },
  {
    id: "78",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.juliette,
  },
  {
    id: "79",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.lara,
  },
  {
    id: "80",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.nicoleChinuntdet,
  },
  {
    id: "81",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.nicoleSievers,
  },
  {
    id: "82",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.sara,
  },
  {
    id: "83",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.sarah,
  },
  {
    id: "84",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.sasha,
  },
  {
    id: "85",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.sidra,
  },
  {
    id: "86",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.thiago,
  },
  {
    id: "87",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.will,
  },
  {
    id: "88",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.wyatt,
  },
  {
    id: "89",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.yuang,
  },
  {
    id: "90",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-24",
    endDate: "2026-01-02",
    allDay: true,
    person: people.arnie,
  },

  // November 30 - one of each event type
  {
    id: "91",
    title: "PTO",
    type: "time-off",
    startDate: "2025-11-30",
    allDay: true,
    person: people.arnie,
    description: "Personal day",
  },
  {
    id: "92",
    title: "Birthday",
    type: "birthday",
    startDate: "2025-11-30",
    allDay: true,
    person: people.adam,
  },
  {
    id: "93",
    title: "2 Years at Warp",
    type: "anniversary",
    startDate: "2025-11-30",
    allDay: true,
    person: people.aj,
    metadata: { yearsOfService: 2 },
  },
  {
    id: "94",
    title: "49ers @ Browns",
    type: "company-event",
    startDate: "2025-11-30T10:00:00-08:00",
    endDate: "2025-11-30T12:00:00-08:00",
    description: "Weekly team sync",
  },
  {
    id: "101",
    title: "F1 Qatar Grand Prix",
    type: "company-event",
    startDate: "2025-11-30T08:00:00-08:00",
    endDate: "2025-11-30T10:00:00-08:00",
    description: "Formula 1 race",
  },
  {
    id: "95",
    title: "Design Engineer Assignment Due",
    type: "deadline",
    startDate: "2025-11-30T17:00:00-08:00",
    description: "End of design engineer assignment period",
  },

  // December 1 - one of each event type
  {
    id: "96",
    title: "PTO",
    type: "time-off",
    startDate: "2025-12-01",
    allDay: true,
    person: people.grayson,
    description: "Doctor appointment",
  },
  {
    id: "97",
    title: "Birthday",
    type: "birthday",
    startDate: "2025-12-01",
    allDay: true,
    person: people.lara,
  },
  {
    id: "98",
    title: "3 Years at Warp",
    type: "anniversary",
    startDate: "2025-12-01",
    allDay: true,
    person: people.benjamin,
    metadata: { yearsOfService: 3 },
  },
  {
    id: "99",
    title: "All Hands",
    type: "company-event",
    startDate: "2025-12-01T10:00:00-08:00",
    endDate: "2025-12-01T11:00:00-08:00",
    description: "Monthly all hands meeting",
  },
  {
    id: "100",
    title: "Code Freeze",
    type: "deadline",
    startDate: "2025-12-01T18:00:00-08:00",
    description: "December code freeze deadline",
  },
];

export async function GET() {
  return new Response(JSON.stringify(sampleEvents));
}
